---
  - name: Installing DB2 pre requisites packages - RedHat
    yum:
     name: "{{ db2_packages }}"
     state: present
     update_cache: "{{ make_cache }}"
     disable_gpg_check: yes
    tags: ['packages', 'setup']